#!/usr/bin/env python
"""Further Stage-2 rounds: push every axis on which the current 8-image winner still sits on the edge of everything tried.

    python scripts/hpo_stage2_round.py --model pmf --stage1 outputs/hpo_pmf --stage2 outputs/stage2_pmf [--stage2 outputs/stage2_pmf_r2 ...] \
        --out configs/experiments_hpo_stage2_pmf_r2.yaml

Ranking uses ONLY the 8-image Stage-2 rows (4-image Stage-1 scores are not comparable).  The grid is the union of
every value tried in Stage 1 and all Stage-2 rounds, so a winner that sits on the extreme of that union is pushed one
more step (hpo_stage2.extend), and the round is finished when no cell needs a push.  Cells with no push are omitted.
"""
import argparse, collections, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import hpo_stage2 as H

# the YAML per-model batch sizes hpo_stage2 uses
def batch_for(model, method, key):
    if method == "rhso" and (key[0] or 0) >= 8:
        return H.BATCH_RHSO_LONG[model]
    return H.BATCH[(model, method)]


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--model", required=True); p.add_argument("--stage1", action="append", required=True)
    p.add_argument("--stage2", action="append", required=True); p.add_argument("--out", required=True)
    p.add_argument("--images", type=int, default=8); p.add_argument("--pool", default="cache/data/imagenet_val_100")
    a = p.parse_args()
    _, grids = H.load(a.stage1 + a.stage2)            # union grid
    cells, _ = H.load(a.stage2)                        # ranking: 8-image rows only
    new = collections.defaultdict(list)                # (problem, method) -> [(key, why)]
    print("%-4s %-17s %-12s %-46s %8s %s" % ("mdl", "problem", "method", "winner (8 img)", "LPIPS", "pushes"))
    for problem in H.PROBLEMS:
        for method in H.METHODS:
            cell = (a.model, problem, method)
            if cell not in cells: continue
            ranked = sorted(cells[cell].items(), key=lambda kv: kv[1]["lpips"])
            win_key, win = ranked[0]; notes = []
            for i, knob in enumerate(H.KNOBS[method]):
                v = win_key[i]; grid = grids[(a.model, method)][knob]
                if v is None or len(grid) < 2: continue
                g = sorted(grid)
                for direction, edge in ((-1, g[0]), (+1, g[-1])):
                    if abs(v - edge) <= 1e-9 * max(1, abs(edge)):
                        nv = H.extend(v, knob, grid, direction)
                        if nv is None: notes.append("%s=%s hard bound" % (knob, H.fmt(v, knob))); continue
                        k2 = list(win_key); k2[i] = nv
                        if not any(H.same(tuple(k2), k) for k in cells[cell]):
                            new[(problem, method)].append((tuple(k2), "edge:%s%s" % (knob, "+" if direction > 0 else "-")))
                            notes.append("%s=%s -> %s" % (knob, H.fmt(v, knob), H.fmt(nv, knob)))
            desc = "  ".join("%s=%s" % (k, H.fmt(v, k)) for k, v in zip(H.KNOBS[method], win_key))
            print("%-4s %-17s %-12s %-46s %8.4f %s" % (a.model, problem, method, desc, win["lpips"], "; ".join(notes)))
    if not new:
        print("\nno cell needs another push: every winner has a worse neighbour on both sides (or a hard bound)"); return
    lines = ['''# Stage-2 follow-up round for %s (generated by scripts/hpo_stage2_round.py from %s):
# one step further out on every axis where the 8-image winner still sat on the edge of everything tried.
runtime:
  seed: 42
  accelerator: auto
  output_root: outputs
  cache_root: cache
  release_model_after_use: true
  continue_on_experiment_error: true
  progress_bars: false
  save_individual_images: true
  verbose: true
  max_atomic_jobs: 4000
  resume: true
  replicate: 0
  gpu_memory_profiling: true
  nvml_sample_interval: 0.02

data:
  source: local_folder
  local_folder: "%s"
  image_size: 256

models:
  %s: {}%s

defaults:
  control_cost_normalization: sum_squared
  optimizer: adam
  warm_start: false
  grad_clip: null
  record_loss_history: false

metrics:
  lpips: true
  lpips_net: alex

experiments:
''' % (a.model, ", ".join(a.stage2), a.pool, a.model, "\n    variant: JiT-B/16" if a.model == "jit" else "")]
    n = 0
    for (problem, method), cands in new.items():
        for i, (k, why) in enumerate(cands):
            n += 1
            fields = ["t0: 1.0"] + ([H.FIXED[method][a.model]] if H.FIXED[method][a.model] else [])
            fields += ["%s: %s" % (kn, H.fmt(v, kn)) for kn, v in zip(H.KNOBS[method], k) if v is not None]
            lines.append("\n  %s__%s__x%d:" % (H.EXP_NAME[problem], method, i + 1))
            lines.append("    enabled: true\n    problem: %s\n    num_images: %d\n    degradation: %s\n    models:\n      %s:\n        batch_size: %d\n        methods:\n          %s: {%s}   # %s"
                         % (problem, a.images, H.DEGRADATION[problem], a.model, batch_for(a.model, method, k), method, ", ".join(fields), why))
    Path(a.out).write_text("\n".join(lines) + "\n")
    print("\nwrote %s: %d jobs at %d images" % (a.out, n, a.images))


if __name__ == "__main__":
    main()
