#!/usr/bin/env python
"""Capacity-matched RHSO stage-count sweeps: write the two N-sweep configurations.

    python scripts/make_theory_N_configs.py

Writes configs/experiments_theory_N_fixedB_final100.yaml (B = N*M = 160, N in 1..32) and
configs/experiments_theory_N_fixedM_final100.yaml (M = 40, N in 1..16) for two capacity-matched
pairs: pMF-L/16 vs JiT-L/16 in pixel space and iMF-XL/2 vs SiT-XL/2 in latent space.  Only RHSO
runs, with direct terminal planning, t0 = 1, beta = 1, and per-task lr / mu frozen at the
frozen-100 benchmark winners (docs/best_hyperparameters.md); nothing is retuned per N or per
model size.  Each (task, N) pair is its own experiment block so N and M never form a product.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROBLEMS = [("denoising", "denoising", "{sigma: 0.2}"),
            ("deblur", "deblurring", "{sigma: 0.05, blur_sigma: 1.0, kernel_size: 7, padding: reflect}"),
            ("super_resolution", "super_resolution", "{factor: 2, sigma: 0.05}"),
            ("random_inpaint", "random_inpainting", "{missing_fraction: 0.7, sigma: 0.01}"),
            ("box_inpaint", "box_inpainting", "{box: 40, sigma: 0.05}")]
MODELS = ["pmf", "jit", "imf", "sit"]
# (lr, mu) per (model, problem): the frozen-100 grid-only RHSO winners.  SiT / iMF values are
# reused unchanged for the capacity-matched variants (iMF-XL/2 is not tuned separately).
FROZEN = {
    "jit": {"denoising": (0.005, 0.2), "deblur": (0.01, 0.0), "super_resolution": (0.01, 0.2),
            "random_inpaint": (0.01, 0.0), "box_inpaint": (0.01, 0.0)},
    "pmf": {"denoising": (0.03, 1.0), "deblur": (0.01, 0.0), "super_resolution": (0.01, 0.2),
            "random_inpaint": (0.01, 0.0), "box_inpaint": (0.01, 0.0)},
    "sit": {p: (0.03, 0.0) for p, _, _ in PROBLEMS},
    "imf": {p: (0.03, 0.0) for p, _, _ in PROBLEMS},
}
SOLVER = {"jit": ", solver: heun", "sit": ", solver: heun", "pmf": "", "imf": ""}
PROTOCOLS = {
    "fixedB": dict(tag="B160", pairs=[(1, 160), (2, 80), (4, 40), (8, 20), (16, 10), (32, 5)],
                   title="FIXED TOTAL OPTIMISER BUDGET  B = N*M = 160",
                   note="M = 160 / N shrinks as N grows: is replanning worth the iterations it costs?"),
    "fixedM": dict(tag="M40", pairs=[(1, 40), (2, 40), (4, 40), (8, 40), (16, 40)],
                   title="FIXED PER-STAGE OPTIMISER BUDGET  M = 40",
                   note="B = 40 N grows from 40 to 640 (deliberately unmatched): does replanning help when nothing is taken away?"),
}

HEADER = """# =====================================================================================
# CAPACITY-MATCHED RHSO STAGE-COUNT SWEEP -- {title}
# =====================================================================================
# Generated by scripts/make_theory_N_configs.py.  {note}
#
# Pairs: pMF-L/16 vs JiT-L/16 (pixel), iMF-XL/2 vs SiT-XL/2 (latent).  RHSO only, direct
# terminal planning (one clean-state prediction per objective for both families), t0 = 1,
# beta = 1, 100 frozen images, seed 42.  lr and mu per task are the frozen-100 benchmark
# winners (docs/best_hyperparameters.md) and are NOT retuned per N or per model size; SiT and
# iMF-B values are reused for SiT-XL/2 and iMF-XL/2.
#
#   python run.py --config {path} --dry-run
#   python run.py --config {path} --models pmf --run-id theory_{key}_pmf --no-figures
#
# Expected scale: 5 tasks x {n_pairs} N values x 4 models = {n_jobs} atomic jobs.
# =====================================================================================

runtime:
  seed: 42
  accelerator: auto
  output_root: outputs
  cache_root: cache
  release_model_after_use: auto
  continue_on_experiment_error: true
  progress_bars: false
  save_individual_images: false
  verbose: true
  max_atomic_jobs: 256
  resume: true
  replicate: 0
  gpu_memory_profiling: true
  nvml_sample_interval: 0.02

data:
  # The SAME frozen ImageNet-100 benchmark the final paper configuration uses
  # (class seed 42, image seed 43). Point `local_folder` at your copy.
  source: local_folder
  local_folder: /home/abdelaal/controllable-image-generation-benchmarks/imagenet100_c42_i43
  image_size: 256

models:
  pmf:
    batch_size: 10
  jit:
    variant: JiT-L/16
    batch_size: 4
  imf:
    display_name: iMF-XL/2
    ckpt_file: iMF-XL-2.zip
    model_str: imfDiT_XL_2
    guidance: {{scale: 8.0, interval: [0.42, 0.62], mode: null}}   # the repository's recommendation for iMF-XL/2
    batch_size: 2
  sit:
    batch_size: 6

defaults:
  control_cost_normalization: sum_squared
  optimizer: adam
  warm_start: false
  grad_clip: null
  record_loss_history: false

metrics:
  lpips: true
  lpips_net: alex

experiments:
"""


def main():
    for key, proto in PROTOCOLS.items():
        path = "configs/experiments_theory_N_%s_final100.yaml" % key
        n_jobs = len(PROBLEMS) * len(proto["pairs"]) * len(MODELS)
        out = [HEADER.format(title=proto["title"], note=proto["note"], path=path, key=key,
                             n_pairs=len(proto["pairs"]), n_jobs=n_jobs)]
        for problem, _, degradation in PROBLEMS:
            for n, m in proto["pairs"]:
                out.append("\n  %s_%s_N%d:" % (problem, proto["tag"], n))
                out.append("    enabled: true\n    problem: %s\n    num_images: 100\n    degradation: %s"
                           "\n    defaults: {t0: 1.0, beta: 1.0}\n    models:" % (problem, degradation))
                for model in MODELS:
                    lr, mu = FROZEN[model][problem]
                    out.append("      %s:\n        methods:\n          rhso: {num_rhso_steps: %d, num_opt_steps: %d, lr: %g, mu: %g, optimizer: adam%s, rhso_terminal_mode: direct,"
                               "\n                  rhso_stage_diagnostics: true, rhso_consistency_diagnostics: true, rhso_jacobian_diagnostics: false}"
                               % (model, n, m, lr, mu, SOLVER[model]))
        (ROOT / path).write_text("\n".join(out) + "\n")
        print("wrote %s (%d jobs)" % (path, n_jobs))


if __name__ == "__main__":
    main()
